spring:
  application:
    name: order-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8084/realms/flash-sale-realm

server:
  port: 8081