package flashsalesystem.orderservice.enums;

public enum OrderResults
{
    SUCCESS, INSUFFICIENT_STOCK, PRODUCT_NOT_FOUND, PAYMENT_FAILED, PAYMENT_PROCESSING_ERROR, UNKNOWN_PAYMENT_ERROR, UNKNOWN_RESERVATION_ERROR, UNKNOWN_ERROR
}
